#pragma once

extern "C" {
#include "Str.h"
#include "Term.h"
#include "MemoryManager.h"
#include "Tokenizer.h"
#include "Number.h"
#include "Pair.h"
#include "Dictionary.h"
#include "Redex.h"
#include "Parser.h"
#include "Definitions.h"
#include "Character.h"
#include "String.h"
#include "Boolean.h"
#include "Error.h"
#include "Library.h"
#include "Evaluation.h"
#include "TermEvaluation.h"
#include "TermListEvaluation.h"
#include "RedexEvaluation.h"
#include "LetEvaluation.h"
#include "DefineEvaluation.h"
#include "Evaluation.h"
}